### ISSUE TITLE
Make nodes (commits, branches, tags) to be HTML links.

### ISSUE THREAD

**Issue by drdv** [drdv/git-dag#90]
It is convenient to click on a node and see (in another browser tab) say github's commit details. To achieve this we need to have info like:

```
  github:
    base: "https://github.com"
    commit: "{base}/{user}/{project}/commit/{commit}"
    branch: "{base}/{user}/{project}/tree/{branch}"
    tag: "{base}/{user}/{project}/releases/tag/{tag}"

  bitbucket:
    base: "https://bitbucket.org"
    commit: "{base}/{user}/{project}/commits/{commit}"
    branch: "{base}/{user}/{project}/src/{branch}"
    tag: "{base}/{user}/{project}/src/{tag}"
``` 

The user can add more provides to the config.
